package com.example.demo.model;

import java.io.Serializable;
import java.util.Date;
import org.joda.money.Money;

public class CoffeeNew implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coffeenew.id
     *
     * @mbg.generated Wed Aug 21 09:35:39 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coffeenew.name
     *
     * @mbg.generated Wed Aug 21 09:35:39 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coffeenew.price
     *
     * @mbg.generated Wed Aug 21 09:35:39 CST 2019
     */
    private Money price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coffeenew.create_time
     *
     * @mbg.generated Wed Aug 21 09:35:39 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coffeenew.update_time
     *
     * @mbg.generated Wed Aug 21 09:35:39 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_coffeenew
     *
     * @mbg.generated Wed Aug 21 09:35:39 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coffeenew.id
     *
     * @return the value of t_coffeenew.id
     *
     * @mbg.generated Wed Aug 21 09:35:39 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coffeenew
     *
     * @mbg.generated Wed Aug 21 09:35:39 CST 2019
     */
    public CoffeeNew withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coffeenew.id
     *
     * @param id the value for t_coffeenew.id
     *
     * @mbg.generated Wed Aug 21 09:35:39 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coffeenew.name
     *
     * @return the value of t_coffeenew.name
     *
     * @mbg.generated Wed Aug 21 09:35:39 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coffeenew
     *
     * @mbg.generated Wed Aug 21 09:35:39 CST 2019
     */
    public CoffeeNew withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coffeenew.name
     *
     * @param name the value for t_coffeenew.name
     *
     * @mbg.generated Wed Aug 21 09:35:39 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coffeenew.price
     *
     * @return the value of t_coffeenew.price
     *
     * @mbg.generated Wed Aug 21 09:35:39 CST 2019
     */
    public Money getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coffeenew
     *
     * @mbg.generated Wed Aug 21 09:35:39 CST 2019
     */
    public CoffeeNew withPrice(Money price) {
        this.setPrice(price);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coffeenew.price
     *
     * @param price the value for t_coffeenew.price
     *
     * @mbg.generated Wed Aug 21 09:35:39 CST 2019
     */
    public void setPrice(Money price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coffeenew.create_time
     *
     * @return the value of t_coffeenew.create_time
     *
     * @mbg.generated Wed Aug 21 09:35:39 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coffeenew
     *
     * @mbg.generated Wed Aug 21 09:35:39 CST 2019
     */
    public CoffeeNew withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coffeenew.create_time
     *
     * @param createTime the value for t_coffeenew.create_time
     *
     * @mbg.generated Wed Aug 21 09:35:39 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coffeenew.update_time
     *
     * @return the value of t_coffeenew.update_time
     *
     * @mbg.generated Wed Aug 21 09:35:39 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coffeenew
     *
     * @mbg.generated Wed Aug 21 09:35:39 CST 2019
     */
    public CoffeeNew withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coffeenew.update_time
     *
     * @param updateTime the value for t_coffeenew.update_time
     *
     * @mbg.generated Wed Aug 21 09:35:39 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coffeenew
     *
     * @mbg.generated Wed Aug 21 09:35:39 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", price=").append(price);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}