package com.example.demo.mapper;

import com.example.demo.model.CoffeeNew;
import com.example.demo.model.CoffeeNewExample;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.session.RowBounds;

public interface CoffeeNewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coffeenew
     *
     * @mbg.generated Wed Aug 21 09:35:39 CST 2019
     */
    long countByExample(CoffeeNewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coffeenew
     *
     * @mbg.generated Wed Aug 21 09:35:39 CST 2019
     */
    int deleteByExample(CoffeeNewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coffeenew
     *
     * @mbg.generated Wed Aug 21 09:35:39 CST 2019
     */
    @Delete({
        "delete from t_coffeenew",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coffeenew
     *
     * @mbg.generated Wed Aug 21 09:35:39 CST 2019
     */
    @Insert({
        "insert into t_coffeenew (name, price, ",
        "create_time, update_time)",
        "values (#{name,jdbcType=VARCHAR}, #{price,jdbcType=BIGINT,typeHandler=com.example.demo.handler.MoneyTypeHandler}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
//    @SelectKey(statement="CALL IDENTITY()", keyProperty="id", before=false, resultType=Long.class)
    @Options(keyProperty = "id", useGeneratedKeys = true)
    int insert(CoffeeNew record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coffeenew
     *
     * @mbg.generated Wed Aug 21 09:35:39 CST 2019
     */
    int insertSelective(CoffeeNew record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coffeenew
     *
     * @mbg.generated Wed Aug 21 09:35:39 CST 2019
     */
    List<CoffeeNew> selectByExampleWithRowbounds(CoffeeNewExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coffeenew
     *
     * @mbg.generated Wed Aug 21 09:35:39 CST 2019
     */
    List<CoffeeNew> selectByExample(CoffeeNewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coffeenew
     *
     * @mbg.generated Wed Aug 21 09:35:39 CST 2019
     */
    @Select({
        "select",
        "id, name, price, create_time, update_time",
        "from t_coffeenew",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.example.demo.mapper.CoffeeNewMapper.BaseResultMap")
    CoffeeNew selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coffeenew
     *
     * @mbg.generated Wed Aug 21 09:35:39 CST 2019
     */
    int updateByExampleSelective(@Param("record") CoffeeNew record, @Param("example") CoffeeNewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coffeenew
     *
     * @mbg.generated Wed Aug 21 09:35:39 CST 2019
     */
    int updateByExample(@Param("record") CoffeeNew record, @Param("example") CoffeeNewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coffeenew
     *
     * @mbg.generated Wed Aug 21 09:35:39 CST 2019
     */
    int updateByPrimaryKeySelective(CoffeeNew record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coffeenew
     *
     * @mbg.generated Wed Aug 21 09:35:39 CST 2019
     */
    @Update({
        "update t_coffeenew",
        "set name = #{name,jdbcType=VARCHAR},",
          "price = #{price,jdbcType=BIGINT,typeHandler=com.example.demo.handler.MoneyTypeHandler},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(CoffeeNew record);
}